name: control_3d
description: "Control 3D - 3D Printer Control App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_libserialport: ^0.4.0
  fl_chart: ^0.70.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "control3d.png"
  android:
    generate: true
  ios:
    generate: true
  macos:
    generate: true
  web:
    generate: true
  windows:
    generate: true
  remove_alpha_ios: true
